### ISSUE TITLE
Lale olan yazarların yorumlarının görünmesi

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#16]
Bu yönetimsel bir karar mı yoksa bug mı bilemiyorum ama lale olan yazarlaın yorumları başlıkta görülmeli mi emin olamadım. Tartışılabilir bir konu olduğunu düşünüyorum.

**Comment by FatihErdem** [comment]
Lale olanlar surelı ucuruluyormus. Profil safyasında bu belirtilebilir.

**Comment by canarslan12** [comment]
Başlığı lale süresi profilde yazsın diye değişsene o zaman
