### ISSUE TITLE
Arama kutusu optimizasyonu

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#18]
Direkt olarak örnekle açıklayacağım.

![screenshot from 2016-03-12 03-23-00](https://cloud.githubusercontent.com/assets/1693329/13719644/d32dffb0-e801-11e5-9502-d300e24eec32.png)

"python" daha kısa olduğu için aşağıda ancak aranan kelime "python" olduğu için en yukarda olması kullanım kolaylığı açısından daha güzel olur.

**Comment by canarslan12** [comment]
yapıldı
