### ISSUE TITLE
Bazı ufak ayarlamalar

### ISSUE THREAD

**Issue by canarslan12** [YouReads/YouReads#29]
- [ ] Arama kısıtı 3e inecek
- [ ] Enter kısıtı 5e çıkacak
- [x] Gece modu sabitleyebilme
- [ ] Sadece adminin duyuru girebilmesi

**Comment by FatihErdem** [comment]
Gece modu #5 sorununda açıldı.

**Comment by FatihErdem** [comment]
#45 #46 sebebiyle kapatildi. sadece Adminin duyuru girilebilmesi acilacak.
