### ISSUE TITLE
Görünmez yorum giriş modu

### ISSUE THREAD

**Issue by AbdurrahmanSimsek** [YouReads/YouReads#54]
tematik giriş için ya da görünmez bi mod

**Comment by canarslan12** [comment]
Anlamadım :/

**Comment by AbdurrahmanSimsek** [comment]
oturup 100 yorum gircem ama sol framei çökertmek istemiyorum. o halde sabahabırak seçeneği işaretliyorum 100 gişiri yapıyorum peşpeşe ve sabaha başlıkların altına yerleşiyor.

ya da görünmez modu seçiyorum, yazdığım başlıklar sol frame çıkmıyor. döşüyorum 100 200 kimse rahatsız olmuyor.

**Comment by canarslan12** [comment]
Görünmez modu sevdim 👍
