### ISSUE TITLE
Versiyon numaralandırma yapılmalı ve detaylı changelog tutulmalı

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#61]
Hangi sürümde ne değişiklikler yapılmış tutulmalı ve sitede bir sayfada yazılmalı. Ayrıca kullanımının açıklaması da eklenmeli.

**Comment by FatihErdem** [comment]
En alttaki şeride eklenebilir. Basit bir şekilde hangi sürümde hangi değişiklik yapıldı ve neden yapıldı, bunun açıklaması olabilir.

**Comment by kodbilenadam** [comment]
İlk sorun çözüldü. http://youreads.net/versiyon.php sayfası açıldı.
