### ISSUE TITLE
Profil sayfası başlığa yanlış yönlendirme

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#62]
Profil sayfasında yazar adına tıklayınca başlığına gidiyor. Özellik mi bug mı anlayamadım. 

![screenshot from 2016-03-13 23-54-40](https://cloud.githubusercontent.com/assets/1693329/13731648/293ef370-e977-11e5-8986-8566e82c1f93.png)

**Comment by canarslan12** [comment]
Her ne kadar yanlışlık olsa da(tahminime göre) bence özellik sayılabilir

**Comment by AbdurrahmanSimsek** [comment]
özellik bu
