### ISSUE TITLE
Başlık ve kanal engelleme

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#77]
Başlık ve kanal engelleme yapılabilmeli. Kanal engelleme ayalardaki kanallar kısmına eklenebilir. Başlık engelleme içinse tasarım anlamında güzel bir yol bulunabilir.

**Comment by AbdurrahmanSimsek** [comment]
su an birinci öncelik budur. sitenin mahiyeti zarara.uğruyor.

**Comment by FatihErdem** [comment]
#78 ile eklendi acil yapilacaklara.

**Comment by FatihErdem** [comment]
Aklıma bir soru takıldı. Bu işlem server side mi client side mi olacak? Sunucu tarafında yapılırsa sistemi yorma ihtimali var. Ancak clientta local storageda tutulursa  bu sefer de bilgisayar değişince engelli listesine ulasilamayacak.

**Comment by canarslan12** [comment]
Server Side tutulacak. Güzel bir kodlama yapılırsa kasma yapmaz. Ama o kodlamayı ben yapabilir miyim onu bilmiyorum 😄

**Comment by FatihErdem** [comment]
@abiyoureads @anilari @kodbilenadam bunun tasarımı baya önemli. Çop kutusu olup ona mı sürükle bırak yapılacak? Yoksa sol framede başlığa uzun basma olayından sonra hemen yanına bir çarpı mı çıkartmalı? Aklınızda neler var bu konuda?

**Comment by kodbilenadam** [comment]
@FatihErdem Client-side localStorage yapıp youreads++ ile veriyi tutup Chrome ile sync yapabiliriz.

**Comment by AbdurrahmanSimsek** [comment]
mause başlığa geldiğinde başlığın sağındaki yorum sayısı eksi ya da carpiya dönüşecek.

**Comment by FatihErdem** [comment]
@kodbilenadam bunun Firefox'u var, Safari'si var IE'si var. :D

**Comment by FatihErdem** [comment]
@abiyoureads biraz bekleme suresi verebiliriz. misal 3 saniye durunca cikar gibisinden. fare uzerinde gezerken aninda cikmasi goruntu kirliligi yapabilir.

**Comment by AbdurrahmanSimsek** [comment]
evet olabilir. basligi acma suresinin ardindan gelebilir.başlığı gördüm mause getirdim.tiklamak 1 saniye 2. saniye belirebilir. mumkunse tabi

**Comment by canarslan12** [comment]
@kodbilenadam sql komutundan müdehale etmeyi düşünüyorum ben.

**Comment by canarslan12** [comment]
**Part I**
- [x] sql komutu yazıldı.
- [x] kanal engelleme ayarlara eklendi
- [x] başlık engelleme başlık sayfasına eklendi (ajax kullan)
- [x] engelli başlıklar ayarlara eklendi

**Part II**
-  [ ] sol frame hover engelleme

**Comment by AbdurrahmanSimsek** [comment]
ellerinize sağlık, muhteşem bir iş çıkardınız :)
