### ISSUE TITLE
Başlık taşındığı zaman kullanıcıya mesaj gitmesi

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#79]
Başlık taşındığı zaman hangi entrysi hangi başlığa taşınmış bu konuda mesaj atılabilir.

**Comment by canarslan12** [comment]
Bu mesaj var ama taşıyanın bunu seçmesi gerek galiba?

**Comment by AbdurrahmanSimsek** [comment]
bu özellik var. gerekli durumlarda mod tikleyerek gönderiyor başlıktakilere. gerekmiyorsa da göndermiyor. örneğin ufak imla hatası varsa atmıyor ama ciddi bir yönlendirme ise gönderiyor.
