### ISSUE TITLE
Gelişmiş ayarlar sekmesi

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#8]
Detaylı seçenekler "Ayarlar" sayfasında "Detaylı Ayarlar" benzeri bir sekmede bulabilir. Toplu olarak durması düzeni sağlayabilir.

**Comment by FatihErdem** [comment]
Gelişmiş ayarları eklemeden önce mutlaka tasarımı yapılıp siteye eklenmeli.

**Comment by canarslan12** [comment]
öncelikle birisinin ayrıntılı bir şekilde tasarımını, tuş yerleşimini kararlaştırması gerek

**Comment by FatihErdem** [comment]
@anilari @kodbilenadam kod aşamasına geçmeden basit bir taslak yapılabilir. İsterseniz kağıt üzerinde yapabilirim. :)

**Comment by AbdurrahmanSimsek** [comment]
evet yapılmalı görmeliyiz

**Comment by FatihErdem** [comment]
Bunun gibi bir sey işimizi çözebilir şimdilik. Paintle yapmak durumunda kaldım. :D

![capture](https://cloud.githubusercontent.com/assets/1693329/13775467/60832c16-eaad-11e5-8b26-2041b0cc2c0f.JPG)

**Comment by FatihErdem** [comment]
Tercihler kismina gelismis ayarlar alt menusu eklendi.
