### ISSUE TITLE
Sol framede başlık sabitleme

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#84]
Modlar tarafından belirlenecek başlıklar sol framede sabitlenebilir en üste. Başlık açma etkinliği için önemli durumda.

**Comment by AbdurrahmanSimsek** [comment]
böyle bir özelliğe ihtiyacımız yok, dayatma olarak görüyorum. organik yapıya aykırı.

**Comment by FatihErdem** [comment]
5.000 baslik tarzi etkinlikleri nereden duyuracaksin? Sitede o anda sol frame hizli akacak. İnsanlara onu ancak öyle duyurabilirain en kolay.

**Comment by AbdurrahmanSimsek** [comment]
başlık açıyorum, duyuruda paylaşıyorum. herkesin takip ışığı zaten yanıyor. başlık sabitlemek ileride başka türlü sorunlara yol açar. mesela kampanya yapıyoruz sabitleyin derler. bu sefer yorueads her kampanyanın sponsoru olmak durumunda kalır. o yüzden organik olmayan hiçbir özellik koyulmamalı, bugün bize yarın onlara, dün onlaraydı bugün neden bize değil gibi türlü sorunlarla başımız ağrır.
