### ISSUE TITLE
Kısa yoldan "badi" yorumlarını listeleme

### ISSUE THREAD

**Issue by FatihErdem** [YouReads/YouReads#89]
Klavye kısayolu haricinde badilerin yazdıkları çok uzakta kalmış. Kanal çubuğunun sağ tarafına da badi ve son şeklinde ikonlar koyabiliriz. Çubuk biraz daha efektif kullanılmış olur.

**Comment by AbdurrahmanSimsek** [comment]
sol frame üstündeki güncel ve popüler butonları yerine güncel, popüler, badi, son, taslak ikonları.

**Comment by FatihErdem** [comment]
O butonlarin oraya sigmasi icin cok kucuk olmasi gerekecek. Biraz daha kullanisli bir yer lazim bize.

**Comment by AbdurrahmanSimsek** [comment]
bunu denemiş yapmışlardı, whatsapp grubunda görseli mevcut. bu ikonlar doğrudan sol framele ilgili olduğu için sol frame üstü en uygun olan yer. kanal barına vs koymak anlamsız ve düzensiz olur. hatta ekşi sözlüğün bu olayını eleştirmiştim. butonlar mobildeki kanal ikonları kadar olsa kullanışlı olabilir.

**Comment by anilari** [comment]
evet konuşuldu ufak iconlar halinde yapılacak

**Comment by FatihErdem** [comment]
Sol frame'e 6 tane buton eklendi. "bugun", "gundem", "populer", "badi" ve "taslak.
