### ISSUE TITLE
duyuru başlığı takip etmek zorunlu olmaktan çıksın

### ISSUE THREAD

**Issue by AbdurrahmanSimsek** [YouReads/YouReads#92]
bunu istemeyen takip etmesin, bu kısıtı kaldıralım.

**Comment by FatihErdem** [comment]
Buyuk degisiklikler(kullanici sozlesmesi, vs) soz konusu oldugu zaman herkesin duymasi lazim. Zaten cok duyuru yapilmiyor. Gerek yok diye dusunuyorum.

**Comment by anilari** [comment]
ondan önce duyuru başlığına herkes yazamasın kısııt getirelim bence :+1:

**Comment by AbdurrahmanSimsek** [comment]
tamamdır
